// Gerado por scripts/build-edge — arquivos do PWA embutidos.
// Os PNGs dos ícones não ficam aqui: são gerados em memória por icons.ts.
export interface Asset {
  type: string;
  body: string;
}

export const ASSETS: Record<string, Asset> = {
  "/index.html": {
    type: "text/html; charset=utf-8",
    body: [
    "<!DOCTYPE html>\n",
    "<html lang=\"pt-BR\">\n",
    "<head>\n",
    "  <meta charset=\"UTF-8\">\n",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, viewport-fit=cover\">\n",
    "  <meta name=\"description\" content=\"Planejador de casamento: convidados, checklist, padrinhos, fornecedores e contagem regressiva.\">\n",
    "  <meta name=\"theme-color\" content=\"#2f3a2a\">\n",
    "  <title>Nosso Casamento</title>\n",
    "  <link rel=\"manifest\" href=\"manifest.webmanifest\">\n",
    "  <link rel=\"icon\" href=\"icons/icon.svg\" type=\"image/svg+xml\">\n",
    "  <link rel=\"apple-touch-icon\" href=\"icons/icon-192.png\">\n",
    "  <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n",
    "  <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\">\n",
    "  <meta name=\"apple-mobile-web-app-title\" content=\"Casamento\">\n",
    "  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n",
    "  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n",
    "  <link href=\"https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300..700;1,9..144,300..700&family=Karla:ital,wght@0,300..700;1,300..700&display=swap\" rel=\"stylesheet\">\n",
    "  <link rel=\"stylesheet\" href=\"css/styles.css\">\n",
    "</head>\n",
    "<body>\n",
    "\n",
    "  <header class=\"app-header\">\n",
    "    <div class=\"header-inner\">\n",
    "      <div class=\"monogram\" id=\"monogram\">N&amp;N</div>\n",
    "      <div class=\"header-names\">\n",
    "        <h1 id=\"header-couple\">Nosso Casamento</h1>\n",
    "        <p id=\"header-date\">Configure a data do grande dia</p>\n",
    "      </div>\n",
    "      <button class=\"btn-icon\" id=\"btn-config\" aria-label=\"Configurações\" title=\"Configurações\">\n",
    "        <svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 1 1-4 0v-.09a1.65 1.65 0 0 0-1-1.51 1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 1 1 0-4h.09a1.65 1.65 0 0 0 1.51-1 1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33h.09a1.65 1.65 0 0 0 1-1.51V3a2 2 0 1 1 4 0v.09a1.65 1.65 0 0 0 1 1.51h.09a1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82v.09a1.65 1.65 0 0 0 1.51 1H21a2 2 0 1 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z\"/></svg>\n",
    "      </button>\n",
    "    </div>\n",
    "  </header>\n",
    "\n",
    "  <main class=\"app-main\">\n",
    "\n",
    "    <!-- ============ DASHBOARD ============ -->\n",
    "    <section class=\"view is-active\" id=\"view-dashboard\">\n",
    "      <div class=\"countdown-card\">\n",
    "        <p class=\"countdown-label\">Faltam</p>\n",
    "        <div class=\"countdown-grid\" id=\"countdown\">\n",
    "          <div class=\"cd-unit\"><span class=\"cd-num\" id=\"cd-dias\">--</span><span class=\"cd-lbl\">dias</span></div>\n",
    "          <div class=\"cd-unit\"><span class=\"cd-num\" id=\"cd-horas\">--</span><span class=\"cd-lbl\">horas</span></div>\n",
    "          <div class=\"cd-unit\"><span class=\"cd-num\" id=\"cd-min\">--</span><span class=\"cd-lbl\">min</span></div>\n",
    "          <div class=\"cd-unit\"><span class=\"cd-num\" id=\"cd-seg\">--</span><span class=\"cd-lbl\">seg</span></div>\n",
    "        </div>\n",
    "        <p class=\"countdown-date\" id=\"countdown-date\">para o grande dia</p>\n",
    "      </div>\n",
    "\n",
    "      <div class=\"stat-grid\">\n",
    "        <button class=\"stat-card\" data-goto=\"convidados\">\n",
    "          <span class=\"stat-num\" id=\"stat-convidados\">0</span>\n",
    "          <span class=\"stat-lbl\">Convidados</span>\n",
    "          <span class=\"stat-sub\" id=\"stat-convidados-sub\">—</span>\n",
    "        </button>\n",
    "        <button class=\"stat-card\" data-goto=\"checklist\">\n",
    "          <span class=\"stat-num\" id=\"stat-pendencias\">0</span>\n",
    "          <span class=\"stat-lbl\">Pendências</span>\n",
    "          <span class=\"stat-sub\" id=\"stat-pendencias-sub\">—</span>\n",
    "        </button>\n",
    "        <button class=\"stat-card\" data-goto=\"padrinhos\">\n",
    "          <span class=\"stat-num\" id=\"stat-padrinhos\">0</span>\n",
    "          <span class=\"stat-lbl\">Padrinhos</span>\n",
    "          <span class=\"stat-sub\" id=\"stat-padrinhos-sub\">—</span>\n",
    "        </button>\n",
    "        <button class=\"stat-card\" data-goto=\"fornecedores\">\n",
    "          <span class=\"stat-num\" id=\"stat-fornecedores\">0</span>\n",
    "          <span class=\"stat-lbl\">Fornecedores</span>\n",
    "          <span class=\"stat-sub\" id=\"stat-fornecedores-sub\">—</span>\n",
    "        </button>\n",
    "      </div>\n",
    "\n",
    "      <div class=\"card\">\n",
    "        <div class=\"card-head\">\n",
    "          <h2>Orçamento</h2>\n",
    "          <span class=\"card-head-value\" id=\"resumo-orcamento-total\">R$ 0,00</span>\n",
    "        </div>\n",
    "        <div class=\"progress-track\"><div class=\"progress-fill\" id=\"orcamento-progress\"></div></div>\n",
    "        <div class=\"legend\">\n",
    "          <span class=\"legend-item\"><i class=\"dot dot-ok\"></i>Resolvido: <b id=\"resumo-valor-resolvido\">R$ 0,00</b></span>\n",
    "          <span class=\"legend-item\"><i class=\"dot dot-pend\"></i>Pendente: <b id=\"resumo-valor-pendente\">R$ 0,00</b></span>\n",
    "        </div>\n",
    "      </div>\n",
    "\n",
    "      <div class=\"card\">\n",
    "        <div class=\"card-head\">\n",
    "          <h2>Checklist</h2>\n",
    "          <span class=\"card-head-value\" id=\"resumo-checklist-frac\">0/0</span>\n",
    "        </div>\n",
    "        <div class=\"progress-track\"><div class=\"progress-fill\" id=\"checklist-progress\"></div></div>\n",
    "        <ul class=\"mini-list\" id=\"dash-pendentes\"></ul>\n",
    "      </div>\n",
    "\n",
    "      <div class=\"card\">\n",
    "        <div class=\"card-head\"><h2>Convidados por lado</h2></div>\n",
    "        <div class=\"split-bar\" id=\"split-bar\">\n",
    "          <div class=\"split-noiva\" id=\"split-noiva\"></div>\n",
    "          <div class=\"split-noivo\" id=\"split-noivo\"></div>\n",
    "        </div>\n",
    "        <div class=\"legend\">\n",
    "          <span class=\"legend-item\"><i class=\"dot dot-noiva\"></i><span id=\"lado-a-label\">Noiva</span>: <b id=\"resumo-lado-a\">0</b></span>\n",
    "          <span class=\"legend-item\"><i class=\"dot dot-noivo\"></i><span id=\"lado-b-label\">Noivo</span>: <b id=\"resumo-lado-b\">0</b></span>\n",
    "        </div>\n",
    "      </div>\n",
    "    </section>\n",
    "\n",
    "    <!-- ============ CONVIDADOS ============ -->\n",
    "    <section class=\"view\" id=\"view-convidados\">\n",
    "      <div class=\"view-head\">\n",
    "        <h2 class=\"view-title\">Lista de Convidados</h2>\n",
    "        <p class=\"view-sub\" id=\"convidados-resumo\">Nenhum convidado ainda</p>\n",
    "      </div>\n",
    "\n",
    "      <form class=\"form-card\" id=\"form-convidado\">\n",
    "        <input type=\"text\" id=\"convidado-nome\" placeholder=\"Nome do convidado\" required maxlength=\"80\">\n",
    "        <div class=\"form-row\">\n",
    "          <div class=\"seg-control\" role=\"radiogroup\" aria-label=\"Lado\">\n",
    "            <label><input type=\"radio\" name=\"convidado-lado\" value=\"noiva\" checked><span id=\"seg-lado-a\">Noiva</span></label>\n",
    "            <label><input type=\"radio\" name=\"convidado-lado\" value=\"noivo\"><span id=\"seg-lado-b\">Noivo</span></label>\n",
    "          </div>\n",
    "          <label class=\"field-inline\">\n",
    "            <span>+ acomp.</span>\n",
    "            <input type=\"number\" id=\"convidado-acomp\" min=\"0\" max=\"20\" value=\"0\">\n",
    "          </label>\n",
    "          <button type=\"submit\" class=\"btn-primary\">Adicionar</button>\n",
    "        </div>\n",
    "      </form>\n",
    "\n",
    "      <div class=\"filter-row\" id=\"convidados-filtros\">\n",
    "        <button class=\"chip is-active\" data-filtro=\"todos\">Todos</button>\n",
    "        <button class=\"chip\" data-filtro=\"noiva\" id=\"chip-lado-a\">Noiva</button>\n",
    "        <button class=\"chip\" data-filtro=\"noivo\" id=\"chip-lado-b\">Noivo</button>\n",
    "        <button class=\"chip\" data-filtro=\"confirmados\">Confirmados</button>\n",
    "      </div>\n",
    "\n",
    "      <ul class=\"item-list\" id=\"lista-convidados\"></ul>\n",
    "      <p class=\"empty-state\" id=\"convidados-empty\">Adicione o primeiro convidado acima ✨</p>\n",
    "    </section>\n",
    "\n",
    "    <!-- ============ CHECKLIST ============ -->\n",
    "    <section class=\"view\" id=\"view-checklist\">\n",
    "      <div class=\"view-head\">\n",
    "        <h2 class=\"view-title\">Checklist &amp; Custos</h2>\n",
    "        <p class=\"view-sub\" id=\"checklist-resumo\">Nenhum item ainda</p>\n",
    "      </div>\n",
    "\n",
    "      <form class=\"form-card\" id=\"form-item\">\n",
    "        <input type=\"text\" id=\"item-desc\" placeholder=\"O que precisa ser resolvido?\" required maxlength=\"120\">\n",
    "        <div class=\"form-row\">\n",
    "          <label class=\"field-inline field-money\">\n",
    "            <span>R$</span>\n",
    "            <input type=\"text\" id=\"item-valor\" inputmode=\"decimal\" placeholder=\"0,00\">\n",
    "          </label>\n",
    "          <button type=\"submit\" class=\"btn-primary\">Adicionar</button>\n",
    "        </div>\n",
    "      </form>\n",
    "\n",
    "      <div class=\"totals-strip\">\n",
    "        <div class=\"total-box\"><span class=\"total-lbl\">Total</span><span class=\"total-val\" id=\"total-geral\">R$ 0,00</span></div>\n",
    "        <div class=\"total-box total-ok\"><span class=\"total-lbl\">Resolvido</span><span class=\"total-val\" id=\"total-resolvido\">R$ 0,00</span></div>\n",
    "        <div class=\"total-box total-pend\"><span class=\"total-lbl\">Pendente</span><span class=\"total-val\" id=\"total-pendente\">R$ 0,00</span></div>\n",
    "      </div>\n",
    "\n",
    "      <div class=\"filter-row\" id=\"checklist-filtros\">\n",
    "        <button class=\"chip is-active\" data-filtro=\"todos\">Todos</button>\n",
    "        <button class=\"chip\" data-filtro=\"pendentes\">Pendentes</button>\n",
    "        <button class=\"chip\" data-filtro=\"resolvidos\">Resolvidos</button>\n",
    "      </div>\n",
    "\n",
    "      <ul class=\"item-list\" id=\"lista-itens\"></ul>\n",
    "      <p class=\"empty-state\" id=\"checklist-empty\">Cadastre a primeira tarefa acima ✨</p>\n",
    "    </section>\n",
    "\n",
    "    <!-- ============ PADRINHOS ============ -->\n",
    "    <section class=\"view\" id=\"view-padrinhos\">\n",
    "      <div class=\"view-head\">\n",
    "        <h2 class=\"view-title\">Padrinhos &amp; Madrinhas</h2>\n",
    "        <p class=\"view-sub\" id=\"padrinhos-resumo\">Nenhum par ainda</p>\n",
    "      </div>\n",
    "\n",
    "      <form class=\"form-card\" id=\"form-padrinho\">\n",
    "        <div class=\"form-row form-row-stack\">\n",
    "          <input type=\"text\" id=\"padrinho-nome\" placeholder=\"Padrinho\" required maxlength=\"80\">\n",
    "          <span class=\"amp\">&amp;</span>\n",
    "          <input type=\"text\" id=\"madrinha-nome\" placeholder=\"Madrinha\" required maxlength=\"80\">\n",
    "        </div>\n",
    "        <button type=\"submit\" class=\"btn-primary btn-block\">Adicionar par</button>\n",
    "      </form>\n",
    "\n",
    "      <ul class=\"pair-list\" id=\"lista-padrinhos\"></ul>\n",
    "      <p class=\"empty-state\" id=\"padrinhos-empty\">Adicione o primeiro par acima ✨</p>\n",
    "    </section>\n",
    "\n",
    "    <!-- ============ FORNECEDORES ============ -->\n",
    "    <section class=\"view\" id=\"view-fornecedores\">\n",
    "      <div class=\"view-head\">\n",
    "        <h2 class=\"view-title\">Fornecedores</h2>\n",
    "        <p class=\"view-sub\" id=\"fornecedores-resumo\">Nenhum fornecedor ainda</p>\n",
    "      </div>\n",
    "\n",
    "      <form class=\"form-card\" id=\"form-fornecedor\">\n",
    "        <input type=\"text\" id=\"fornecedor-nome\" placeholder=\"Nome (ex.: Buffet Sabor & Festa)\" required maxlength=\"80\">\n",
    "        <div class=\"form-row\">\n",
    "          <select id=\"fornecedor-categoria\">\n",
    "            <option>Buffet</option>\n",
    "            <option>Fotografia</option>\n",
    "            <option>Música / DJ</option>\n",
    "            <option>Decoração</option>\n",
    "            <option>Espaço / Local</option>\n",
    "            <option>Vestido & Traje</option>\n",
    "            <option>Doces & Bolo</option>\n",
    "            <option>Convites</option>\n",
    "            <option>Cerimonial</option>\n",
    "            <option>Outro</option>\n",
    "          </select>\n",
    "          <input type=\"tel\" id=\"fornecedor-contato\" placeholder=\"WhatsApp / telefone\" maxlength=\"20\">\n",
    "        </div>\n",
    "        <button type=\"submit\" class=\"btn-primary btn-block\">Adicionar fornecedor</button>\n",
    "      </form>\n",
    "\n",
    "      <ul class=\"item-list\" id=\"lista-fornecedores\"></ul>\n",
    "      <p class=\"empty-state\" id=\"fornecedores-empty\">Cadastre o primeiro fornecedor acima ✨</p>\n",
    "    </section>\n",
    "\n",
    "    <!-- ============ CONFIGURAÇÕES ============ -->\n",
    "    <section class=\"view\" id=\"view-config\">\n",
    "      <div class=\"view-head\">\n",
    "        <h2 class=\"view-title\">Nosso Casamento</h2>\n",
    "        <p class=\"view-sub\">Dados do casal e do grande dia</p>\n",
    "      </div>\n",
    "\n",
    "      <form class=\"form-card\" id=\"form-config\">\n",
    "        <label class=\"field\">\n",
    "          <span>Nome da noiva</span>\n",
    "          <input type=\"text\" id=\"config-noiva\" placeholder=\"Ex.: Maria\" maxlength=\"40\">\n",
    "        </label>\n",
    "        <label class=\"field\">\n",
    "          <span>Nome do noivo / noiva</span>\n",
    "          <input type=\"text\" id=\"config-noivo\" placeholder=\"Ex.: João\" maxlength=\"40\">\n",
    "        </label>\n",
    "        <label class=\"field\">\n",
    "          <span>Data e hora do casamento</span>\n",
    "          <input type=\"datetime-local\" id=\"config-data\">\n",
    "        </label>\n",
    "        <label class=\"field\">\n",
    "          <span>Local (opcional)</span>\n",
    "          <input type=\"text\" id=\"config-local\" placeholder=\"Ex.: Estância Bahia\" maxlength=\"80\">\n",
    "        </label>\n",
    "        <button type=\"submit\" class=\"btn-primary btn-block\">Salvar</button>\n",
    "      </form>\n",
    "\n",
    "      <div class=\"card\">\n",
    "        <div class=\"card-head\">\n",
    "          <h2>Sincronizar entre celulares</h2>\n",
    "          <span class=\"sync-status\" id=\"sync-status\"></span>\n",
    "        </div>\n",
    "        <div id=\"sync-off\">\n",
    "          <p class=\"card-text\">Ative para guardar os dados na nuvem e os dois celulares verem as mesmas listas. Vocês compartilham um <b>código secreto do casal</b>.</p>\n",
    "          <button class=\"btn-primary btn-block\" id=\"btn-sync-ativar\" type=\"button\">Ativar sincronização</button>\n",
    "          <p class=\"card-text card-text-meio\">Seu par já ativou? Cole o código aqui:</p>\n",
    "          <div class=\"form-row\">\n",
    "            <input type=\"text\" id=\"sync-codigo-entrada\" placeholder=\"código do casal\" autocomplete=\"off\">\n",
    "            <button class=\"btn-secondary btn-estreito\" id=\"btn-sync-conectar\" type=\"button\">Conectar</button>\n",
    "          </div>\n",
    "        </div>\n",
    "        <div id=\"sync-on\" hidden>\n",
    "          <p class=\"card-text\">Compartilhe este código com seu par (pelo WhatsApp, por exemplo). No outro celular: <b>Configurações → colar o código → Conectar</b>. Guarde-o com carinho: quem tem o código acessa os dados.</p>\n",
    "          <div class=\"form-row\">\n",
    "            <input type=\"text\" id=\"sync-codigo\" readonly>\n",
    "            <button class=\"btn-secondary btn-estreito\" id=\"btn-sync-copiar\" type=\"button\">Copiar</button>\n",
    "          </div>\n",
    "          <button class=\"btn-danger btn-desconectar\" id=\"btn-sync-sair\" type=\"button\">Desconectar este aparelho</button>\n",
    "        </div>\n",
    "      </div>\n",
    "\n",
    "      <div class=\"card\">\n",
    "        <div class=\"card-head\"><h2>Backup dos dados</h2></div>\n",
    "        <p class=\"card-text\">Os dados ficam salvos apenas neste aparelho. Exporte um arquivo de backup para guardar ou levar para outro celular.</p>\n",
    "        <div class=\"form-row\">\n",
    "          <button class=\"btn-secondary\" id=\"btn-exportar\" type=\"button\">Exportar backup</button>\n",
    "          <button class=\"btn-secondary\" id=\"btn-importar\" type=\"button\">Importar backup</button>\n",
    "          <input type=\"file\" id=\"input-importar\" accept=\"application/json\" hidden>\n",
    "        </div>\n",
    "      </div>\n",
    "\n",
    "      <div class=\"card card-danger\">\n",
    "        <div class=\"card-head\"><h2>Zona de perigo</h2></div>\n",
    "        <p class=\"card-text\">Apaga todos os convidados, tarefas, padrinhos e fornecedores deste aparelho.</p>\n",
    "        <button class=\"btn-danger\" id=\"btn-limpar\" type=\"button\">Apagar todos os dados</button>\n",
    "      </div>\n",
    "    </section>\n",
    "  </main>\n",
    "\n",
    "  <nav class=\"bottom-nav\" aria-label=\"Navegação principal\">\n",
    "    <button class=\"nav-item is-active\" data-view=\"dashboard\" aria-label=\"Início\">\n",
    "      <svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 10.5 12 3l9 7.5\"/><path d=\"M5 9.5V21h14V9.5\"/></svg>\n",
    "      <span>Início</span>\n",
    "    </button>\n",
    "    <button class=\"nav-item\" data-view=\"convidados\" aria-label=\"Convidados\">\n",
    "      <svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"9\" cy=\"8\" r=\"3.2\"/><path d=\"M2.8 20c.6-3.4 3.1-5.2 6.2-5.2s5.6 1.8 6.2 5.2\"/><circle cx=\"17\" cy=\"9\" r=\"2.5\"/><path d=\"M15.6 14.4c2.9.1 5 1.7 5.6 4.6\"/></svg>\n",
    "      <span>Convidados</span>\n",
    "    </button>\n",
    "    <button class=\"nav-item\" data-view=\"checklist\" aria-label=\"Checklist\">\n",
    "      <svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"4\" y=\"3.5\" width=\"16\" height=\"17\" rx=\"2.5\"/><path d=\"m8.5 12 2.4 2.4 4.6-4.8\"/></svg>\n",
    "      <span>Checklist</span>\n",
    "    </button>\n",
    "    <button class=\"nav-item\" data-view=\"padrinhos\" aria-label=\"Padrinhos\">\n",
    "      <svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"9\" cy=\"13.5\" r=\"5\"/><circle cx=\"15\" cy=\"13.5\" r=\"5\"/><path d=\"m10.8 6.5 1.2-2 1.2 2\"/></svg>\n",
    "      <span>Padrinhos</span>\n",
    "    </button>\n",
    "    <button class=\"nav-item\" data-view=\"fornecedores\" aria-label=\"Fornecedores\">\n",
    "      <svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 8h16l-1.2 12.2a1.8 1.8 0 0 1-1.8 1.6H7a1.8 1.8 0 0 1-1.8-1.6z\"/><path d=\"M8.5 11V6.5a3.5 3.5 0 0 1 7 0V11\"/></svg>\n",
    "      <span>Fornec.</span>\n",
    "    </button>\n",
    "  </nav>\n",
    "\n",
    "  <div class=\"toast\" id=\"toast\" role=\"status\"></div>\n",
    "\n",
    "  <script src=\"js/app.js\"></script>\n",
    "</body>\n",
    "</html>\n",
    ""
  ].join(""),
  },
  "/css/styles.css": {
    type: "text/css; charset=utf-8",
    body: [
    "/* ============================================================\n",
    "   Nosso Casamento — PWA\n",
    "   Paleta: marfim, verde-oliva profundo, dourado, rosa-chá\n",
    "   Tipografia: Fraunces (display) + Karla (texto)\n",
    "   ============================================================ */\n",
    "\n",
    ":root {\n",
    "  --ivory: #f7f2e9;\n",
    "  --ivory-deep: #efe7d8;\n",
    "  --paper: #fffdf8;\n",
    "  --ink: #2f3a2a;\n",
    "  --ink-soft: #5d6653;\n",
    "  --ink-faint: #8b917f;\n",
    "  --gold: #b3892e;\n",
    "  --gold-soft: #d4b46a;\n",
    "  --rose: #c98a80;\n",
    "  --rose-soft: #f0ded9;\n",
    "  --sage: #7d9070;\n",
    "  --sage-soft: #e2e8da;\n",
    "  --danger: #b0503c;\n",
    "  --ok: #6f8f5e;\n",
    "  --shadow: 0 2px 10px rgba(47, 58, 42, 0.08), 0 12px 32px rgba(47, 58, 42, 0.06);\n",
    "  --radius: 18px;\n",
    "  --nav-h: 64px;\n",
    "  --font-display: \"Fraunces\", Georgia, \"Times New Roman\", serif;\n",
    "  --font-body: \"Karla\", \"Segoe UI\", Tahoma, sans-serif;\n",
    "}\n",
    "\n",
    "* { box-sizing: border-box; margin: 0; padding: 0; }\n",
    "\n",
    "html { -webkit-text-size-adjust: 100%; }\n",
    "\n",
    "body {\n",
    "  font-family: var(--font-body);\n",
    "  color: var(--ink);\n",
    "  background-color: var(--ivory);\n",
    "  background-image:\n",
    "    radial-gradient(ellipse 80% 50% at 50% -10%, rgba(212, 180, 106, 0.18), transparent 60%),\n",
    "    radial-gradient(ellipse 60% 40% at 100% 100%, rgba(201, 138, 128, 0.10), transparent 55%),\n",
    "    url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='140' height='140'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2'/%3E%3C/filter%3E%3Crect width='140' height='140' filter='url(%23n)' opacity='0.035'/%3E%3C/svg%3E\");\n",
    "  min-height: 100vh;\n",
    "  min-height: 100dvh;\n",
    "  padding-bottom: calc(var(--nav-h) + env(safe-area-inset-bottom, 0px));\n",
    "  line-height: 1.5;\n",
    "}\n",
    "\n",
    "button { font-family: inherit; cursor: pointer; }\n",
    "input, select { font-family: inherit; font-size: 1rem; color: var(--ink); }\n",
    "\n",
    "/* ---------- Header ---------- */\n",
    "\n",
    ".app-header {\n",
    "  position: sticky;\n",
    "  top: 0;\n",
    "  z-index: 20;\n",
    "  background: rgba(247, 242, 233, 0.88);\n",
    "  backdrop-filter: blur(10px);\n",
    "  -webkit-backdrop-filter: blur(10px);\n",
    "  border-bottom: 1px solid rgba(179, 137, 46, 0.25);\n",
    "  padding-top: env(safe-area-inset-top, 0px);\n",
    "}\n",
    "\n",
    ".header-inner {\n",
    "  display: flex;\n",
    "  align-items: center;\n",
    "  gap: 14px;\n",
    "  max-width: 680px;\n",
    "  margin: 0 auto;\n",
    "  padding: 12px 18px;\n",
    "}\n",
    "\n",
    ".monogram {\n",
    "  font-family: var(--font-display);\n",
    "  font-style: italic;\n",
    "  font-weight: 500;\n",
    "  font-size: 1.05rem;\n",
    "  color: var(--paper);\n",
    "  background: linear-gradient(140deg, var(--ink) 0%, #46543c 100%);\n",
    "  border: 1.5px solid var(--gold-soft);\n",
    "  width: 46px;\n",
    "  height: 46px;\n",
    "  border-radius: 50%;\n",
    "  display: grid;\n",
    "  place-items: center;\n",
    "  flex-shrink: 0;\n",
    "  letter-spacing: 0.02em;\n",
    "}\n",
    "\n",
    ".header-names { flex: 1; min-width: 0; }\n",
    "\n",
    ".header-names h1 {\n",
    "  font-family: var(--font-display);\n",
    "  font-weight: 550;\n",
    "  font-size: 1.25rem;\n",
    "  letter-spacing: 0.01em;\n",
    "  white-space: nowrap;\n",
    "  overflow: hidden;\n",
    "  text-overflow: ellipsis;\n",
    "}\n",
    "\n",
    ".header-names p {\n",
    "  font-size: 0.78rem;\n",
    "  color: var(--ink-soft);\n",
    "  text-transform: uppercase;\n",
    "  letter-spacing: 0.12em;\n",
    "}\n",
    "\n",
    ".btn-icon {\n",
    "  background: none;\n",
    "  border: none;\n",
    "  color: var(--ink-soft);\n",
    "  padding: 8px;\n",
    "  border-radius: 12px;\n",
    "  display: grid;\n",
    "  place-items: center;\n",
    "  transition: background 0.2s, color 0.2s;\n",
    "}\n",
    ".btn-icon:hover { background: var(--ivory-deep); color: var(--ink); }\n",
    "\n",
    "/* ---------- Layout / views ---------- */\n",
    "\n",
    ".app-main {\n",
    "  max-width: 680px;\n",
    "  margin: 0 auto;\n",
    "  padding: 18px;\n",
    "}\n",
    "\n",
    ".view { display: none; animation: viewIn 0.35s ease both; }\n",
    ".view.is-active { display: block; }\n",
    "\n",
    "@keyframes viewIn {\n",
    "  from { opacity: 0; transform: translateY(10px); }\n",
    "  to { opacity: 1; transform: none; }\n",
    "}\n",
    "\n",
    ".view-head { margin-bottom: 16px; }\n",
    "\n",
    ".view-title {\n",
    "  font-family: var(--font-display);\n",
    "  font-weight: 550;\n",
    "  font-size: 1.65rem;\n",
    "  line-height: 1.15;\n",
    "}\n",
    "\n",
    ".view-sub { color: var(--ink-soft); font-size: 0.9rem; margin-top: 2px; }\n",
    "\n",
    "/* ---------- Countdown ---------- */\n",
    "\n",
    ".countdown-card {\n",
    "  background:\n",
    "    radial-gradient(ellipse 120% 90% at 50% -20%, rgba(212, 180, 106, 0.35), transparent 55%),\n",
    "    linear-gradient(150deg, #33402c 0%, #24301f 100%);\n",
    "  color: var(--ivory);\n",
    "  border-radius: 24px;\n",
    "  padding: 26px 20px 20px;\n",
    "  text-align: center;\n",
    "  box-shadow: var(--shadow);\n",
    "  border: 1px solid rgba(212, 180, 106, 0.4);\n",
    "  margin-bottom: 18px;\n",
    "  position: relative;\n",
    "  overflow: hidden;\n",
    "}\n",
    "\n",
    ".countdown-card::before,\n",
    ".countdown-card::after {\n",
    "  content: \"\";\n",
    "  position: absolute;\n",
    "  width: 120px;\n",
    "  height: 120px;\n",
    "  border: 1px solid rgba(212, 180, 106, 0.25);\n",
    "  border-radius: 50%;\n",
    "}\n",
    ".countdown-card::before { top: -60px; left: -40px; }\n",
    ".countdown-card::after { bottom: -70px; right: -30px; width: 160px; height: 160px; }\n",
    "\n",
    ".countdown-label {\n",
    "  font-family: var(--font-display);\n",
    "  font-style: italic;\n",
    "  font-size: 1rem;\n",
    "  color: var(--gold-soft);\n",
    "  letter-spacing: 0.06em;\n",
    "}\n",
    "\n",
    ".countdown-grid {\n",
    "  display: flex;\n",
    "  justify-content: center;\n",
    "  gap: 10px;\n",
    "  margin: 12px 0 10px;\n",
    "}\n",
    "\n",
    ".cd-unit {\n",
    "  min-width: 64px;\n",
    "  background: rgba(255, 253, 248, 0.07);\n",
    "  border: 1px solid rgba(212, 180, 106, 0.25);\n",
    "  border-radius: 14px;\n",
    "  padding: 10px 6px 8px;\n",
    "  display: flex;\n",
    "  flex-direction: column;\n",
    "}\n",
    "\n",
    ".cd-num {\n",
    "  font-family: var(--font-display);\n",
    "  font-weight: 550;\n",
    "  font-size: 1.8rem;\n",
    "  line-height: 1;\n",
    "  font-variant-numeric: tabular-nums;\n",
    "}\n",
    "\n",
    ".cd-lbl {\n",
    "  font-size: 0.66rem;\n",
    "  text-transform: uppercase;\n",
    "  letter-spacing: 0.14em;\n",
    "  color: var(--gold-soft);\n",
    "  margin-top: 4px;\n",
    "}\n",
    "\n",
    ".countdown-date {\n",
    "  font-size: 0.82rem;\n",
    "  color: rgba(247, 242, 233, 0.75);\n",
    "  letter-spacing: 0.04em;\n",
    "}\n",
    "\n",
    ".countdown-card.is-past .countdown-label { font-size: 1.4rem; }\n",
    "\n",
    "/* ---------- Stat cards ---------- */\n",
    "\n",
    ".stat-grid {\n",
    "  display: grid;\n",
    "  grid-template-columns: repeat(2, 1fr);\n",
    "  gap: 12px;\n",
    "  margin-bottom: 18px;\n",
    "}\n",
    "\n",
    ".stat-card {\n",
    "  background: var(--paper);\n",
    "  border: 1px solid rgba(179, 137, 46, 0.18);\n",
    "  border-radius: var(--radius);\n",
    "  padding: 14px 16px;\n",
    "  text-align: left;\n",
    "  box-shadow: var(--shadow);\n",
    "  display: flex;\n",
    "  flex-direction: column;\n",
    "  gap: 1px;\n",
    "  transition: transform 0.15s, box-shadow 0.15s;\n",
    "}\n",
    ".stat-card:active { transform: scale(0.97); }\n",
    "\n",
    ".stat-num {\n",
    "  font-family: var(--font-display);\n",
    "  font-weight: 550;\n",
    "  font-size: 1.7rem;\n",
    "  line-height: 1.1;\n",
    "  color: var(--ink);\n",
    "}\n",
    "\n",
    ".stat-lbl {\n",
    "  font-size: 0.72rem;\n",
    "  text-transform: uppercase;\n",
    "  letter-spacing: 0.12em;\n",
    "  color: var(--gold);\n",
    "  font-weight: 700;\n",
    "}\n",
    "\n",
    ".stat-sub { font-size: 0.78rem; color: var(--ink-faint); }\n",
    "\n",
    "/* ---------- Cards ---------- */\n",
    "\n",
    ".card {\n",
    "  background: var(--paper);\n",
    "  border: 1px solid rgba(179, 137, 46, 0.18);\n",
    "  border-radius: var(--radius);\n",
    "  padding: 16px 18px;\n",
    "  box-shadow: var(--shadow);\n",
    "  margin-bottom: 16px;\n",
    "}\n",
    "\n",
    ".card-head {\n",
    "  display: flex;\n",
    "  align-items: baseline;\n",
    "  justify-content: space-between;\n",
    "  gap: 10px;\n",
    "  margin-bottom: 10px;\n",
    "}\n",
    "\n",
    ".card-head h2 {\n",
    "  font-family: var(--font-display);\n",
    "  font-weight: 550;\n",
    "  font-size: 1.15rem;\n",
    "}\n",
    "\n",
    ".card-head-value {\n",
    "  font-weight: 700;\n",
    "  font-size: 0.95rem;\n",
    "  color: var(--ink-soft);\n",
    "  font-variant-numeric: tabular-nums;\n",
    "}\n",
    "\n",
    ".card-text { font-size: 0.88rem; color: var(--ink-soft); margin-bottom: 12px; }\n",
    "\n",
    ".progress-track {\n",
    "  height: 10px;\n",
    "  border-radius: 99px;\n",
    "  background: var(--ivory-deep);\n",
    "  overflow: hidden;\n",
    "  margin-bottom: 10px;\n",
    "}\n",
    "\n",
    ".progress-fill {\n",
    "  height: 100%;\n",
    "  width: 0%;\n",
    "  border-radius: 99px;\n",
    "  background: linear-gradient(90deg, var(--sage) 0%, var(--gold-soft) 100%);\n",
    "  transition: width 0.6s cubic-bezier(0.22, 1, 0.36, 1);\n",
    "}\n",
    "\n",
    ".legend { display: flex; flex-wrap: wrap; gap: 6px 18px; font-size: 0.84rem; color: var(--ink-soft); }\n",
    ".legend b { color: var(--ink); font-variant-numeric: tabular-nums; }\n",
    ".legend-item { display: inline-flex; align-items: center; gap: 6px; }\n",
    "\n",
    ".dot { width: 9px; height: 9px; border-radius: 50%; display: inline-block; }\n",
    ".dot-ok { background: var(--ok); }\n",
    ".dot-pend { background: var(--gold-soft); }\n",
    ".dot-noiva { background: var(--rose); }\n",
    ".dot-noivo { background: var(--sage); }\n",
    "\n",
    ".split-bar {\n",
    "  display: flex;\n",
    "  height: 14px;\n",
    "  border-radius: 99px;\n",
    "  overflow: hidden;\n",
    "  background: var(--ivory-deep);\n",
    "  margin-bottom: 10px;\n",
    "}\n",
    ".split-noiva { background: var(--rose); transition: width 0.6s cubic-bezier(0.22, 1, 0.36, 1); }\n",
    ".split-noivo { background: var(--sage); transition: width 0.6s cubic-bezier(0.22, 1, 0.36, 1); }\n",
    "\n",
    ".mini-list { list-style: none; }\n",
    ".mini-list li {\n",
    "  display: flex;\n",
    "  justify-content: space-between;\n",
    "  gap: 10px;\n",
    "  font-size: 0.88rem;\n",
    "  padding: 7px 0;\n",
    "  border-top: 1px dashed rgba(179, 137, 46, 0.25);\n",
    "  color: var(--ink-soft);\n",
    "}\n",
    ".mini-list li:first-child { border-top: none; }\n",
    ".mini-list .mini-valor { color: var(--ink); font-weight: 700; font-variant-numeric: tabular-nums; white-space: nowrap; }\n",
    "\n",
    "/* ---------- Forms ---------- */\n",
    "\n",
    ".form-card {\n",
    "  background: var(--paper);\n",
    "  border: 1px solid rgba(179, 137, 46, 0.18);\n",
    "  border-radius: var(--radius);\n",
    "  padding: 14px;\n",
    "  box-shadow: var(--shadow);\n",
    "  margin-bottom: 14px;\n",
    "  display: flex;\n",
    "  flex-direction: column;\n",
    "  gap: 10px;\n",
    "}\n",
    "\n",
    ".form-card input[type=\"text\"],\n",
    ".form-card input[type=\"tel\"],\n",
    ".form-card input[type=\"number\"],\n",
    ".form-card input[type=\"datetime-local\"],\n",
    ".form-card select {\n",
    "  width: 100%;\n",
    "  border: 1.5px solid var(--ivory-deep);\n",
    "  background: var(--ivory);\n",
    "  border-radius: 12px;\n",
    "  padding: 11px 13px;\n",
    "  transition: border-color 0.2s;\n",
    "  appearance: none;\n",
    "}\n",
    ".form-card input:focus, .form-card select:focus {\n",
    "  outline: none;\n",
    "  border-color: var(--gold-soft);\n",
    "}\n",
    "\n",
    ".form-row { display: flex; gap: 10px; align-items: stretch; }\n",
    ".form-row > * { min-width: 0; }\n",
    ".form-row select, .form-row input { flex: 1; }\n",
    "\n",
    ".form-row-stack { align-items: center; }\n",
    ".amp {\n",
    "  font-family: var(--font-display);\n",
    "  font-style: italic;\n",
    "  font-size: 1.3rem;\n",
    "  color: var(--gold);\n",
    "  flex-shrink: 0;\n",
    "}\n",
    "\n",
    ".field { display: flex; flex-direction: column; gap: 5px; }\n",
    ".field > span {\n",
    "  font-size: 0.74rem;\n",
    "  font-weight: 700;\n",
    "  text-transform: uppercase;\n",
    "  letter-spacing: 0.1em;\n",
    "  color: var(--ink-soft);\n",
    "}\n",
    "\n",
    ".field-inline {\n",
    "  display: flex;\n",
    "  align-items: center;\n",
    "  gap: 6px;\n",
    "  background: var(--ivory);\n",
    "  border: 1.5px solid var(--ivory-deep);\n",
    "  border-radius: 12px;\n",
    "  padding: 0 10px;\n",
    "  flex-shrink: 0;\n",
    "}\n",
    ".field-inline > span { font-size: 0.8rem; font-weight: 700; color: var(--ink-soft); white-space: nowrap; }\n",
    ".field-inline input {\n",
    "  border: none !important;\n",
    "  background: none !important;\n",
    "  width: 52px;\n",
    "  padding: 11px 0 !important;\n",
    "  text-align: center;\n",
    "}\n",
    ".field-money { flex: 1; }\n",
    ".field-money input { width: 100%; text-align: left; }\n",
    "\n",
    ".seg-control {\n",
    "  display: flex;\n",
    "  background: var(--ivory);\n",
    "  border: 1.5px solid var(--ivory-deep);\n",
    "  border-radius: 12px;\n",
    "  overflow: hidden;\n",
    "  flex: 1;\n",
    "}\n",
    ".seg-control label { flex: 1; display: flex; position: relative; }\n",
    ".seg-control input { position: absolute; opacity: 0; pointer-events: none; }\n",
    ".seg-control span {\n",
    "  flex: 1;\n",
    "  text-align: center;\n",
    "  padding: 11px 6px;\n",
    "  font-size: 0.88rem;\n",
    "  font-weight: 700;\n",
    "  color: var(--ink-faint);\n",
    "  transition: background 0.2s, color 0.2s;\n",
    "  white-space: nowrap;\n",
    "  overflow: hidden;\n",
    "  text-overflow: ellipsis;\n",
    "}\n",
    ".seg-control input:checked + span { background: var(--ink); color: var(--ivory); }\n",
    "\n",
    "#form-convidado .form-row { flex-wrap: wrap; }\n",
    "#form-convidado .seg-control { flex-basis: 100%; }\n",
    "#form-convidado .field-inline { flex: 1; }\n",
    "#form-convidado .field-inline input { width: 100%; }\n",
    "\n",
    "/* ---------- Totais do checklist ---------- */\n",
    "\n",
    ".totals-strip {\n",
    "  display: grid;\n",
    "  grid-template-columns: repeat(3, 1fr);\n",
    "  gap: 10px;\n",
    "  margin-bottom: 14px;\n",
    "}\n",
    "\n",
    ".total-box {\n",
    "  background: var(--paper);\n",
    "  border: 1px solid rgba(179, 137, 46, 0.18);\n",
    "  border-radius: 14px;\n",
    "  padding: 10px 12px;\n",
    "  display: flex;\n",
    "  flex-direction: column;\n",
    "  gap: 2px;\n",
    "  box-shadow: 0 1px 4px rgba(47, 58, 42, 0.05);\n",
    "}\n",
    "\n",
    ".total-lbl {\n",
    "  font-size: 0.66rem;\n",
    "  font-weight: 800;\n",
    "  text-transform: uppercase;\n",
    "  letter-spacing: 0.1em;\n",
    "  color: var(--ink-faint);\n",
    "}\n",
    "\n",
    ".total-val {\n",
    "  font-family: var(--font-display);\n",
    "  font-weight: 550;\n",
    "  font-size: 1.02rem;\n",
    "  font-variant-numeric: tabular-nums;\n",
    "  color: var(--ink);\n",
    "  white-space: nowrap;\n",
    "  overflow: hidden;\n",
    "  text-overflow: ellipsis;\n",
    "}\n",
    "\n",
    ".total-ok { border-color: rgba(111, 143, 94, 0.45); }\n",
    ".total-ok .total-lbl { color: var(--ok); }\n",
    ".total-pend { border-color: rgba(212, 180, 106, 0.6); }\n",
    ".total-pend .total-lbl { color: var(--gold); }\n",
    "\n",
    "/* ---------- Buttons ---------- */\n",
    "\n",
    ".btn-primary {\n",
    "  background: linear-gradient(140deg, var(--ink) 0%, #46543c 100%);\n",
    "  color: var(--ivory);\n",
    "  border: none;\n",
    "  border-radius: 12px;\n",
    "  padding: 11px 20px;\n",
    "  font-weight: 700;\n",
    "  font-size: 0.92rem;\n",
    "  letter-spacing: 0.03em;\n",
    "  flex-shrink: 0;\n",
    "  transition: transform 0.15s, filter 0.2s;\n",
    "}\n",
    ".btn-primary:active { transform: scale(0.97); }\n",
    ".btn-primary:hover { filter: brightness(1.12); }\n",
    "\n",
    ".btn-block { width: 100%; }\n",
    "\n",
    ".btn-secondary {\n",
    "  background: var(--ivory);\n",
    "  color: var(--ink);\n",
    "  border: 1.5px solid var(--gold-soft);\n",
    "  border-radius: 12px;\n",
    "  padding: 10px 16px;\n",
    "  font-weight: 700;\n",
    "  font-size: 0.88rem;\n",
    "  flex: 1;\n",
    "  transition: background 0.2s;\n",
    "}\n",
    ".btn-secondary:hover { background: var(--ivory-deep); }\n",
    "\n",
    ".btn-danger {\n",
    "  background: none;\n",
    "  color: var(--danger);\n",
    "  border: 1.5px solid var(--danger);\n",
    "  border-radius: 12px;\n",
    "  padding: 10px 16px;\n",
    "  font-weight: 700;\n",
    "  font-size: 0.88rem;\n",
    "  width: 100%;\n",
    "  transition: background 0.2s, color 0.2s;\n",
    "}\n",
    ".btn-danger:hover { background: var(--danger); color: var(--paper); }\n",
    "\n",
    ".card-danger { border-color: rgba(176, 80, 60, 0.35); }\n",
    "\n",
    "/* ---------- Sincronização ---------- */\n",
    "\n",
    ".sync-status {\n",
    "  font-size: 0.72rem;\n",
    "  font-weight: 800;\n",
    "  text-transform: uppercase;\n",
    "  letter-spacing: 0.08em;\n",
    "}\n",
    ".sync-status.is-ok { color: var(--ok); }\n",
    ".sync-status.is-erro { color: var(--gold); }\n",
    "\n",
    ".card-text-meio { margin: 14px 0 8px; }\n",
    "\n",
    ".card .form-row input[type=\"text\"] {\n",
    "  width: 100%;\n",
    "  border: 1.5px solid var(--ivory-deep);\n",
    "  background: var(--ivory);\n",
    "  border-radius: 12px;\n",
    "  padding: 11px 13px;\n",
    "  min-width: 0;\n",
    "}\n",
    ".card .form-row input[type=\"text\"]:focus { outline: none; border-color: var(--gold-soft); }\n",
    "#sync-codigo { font-size: 0.8rem; color: var(--ink-soft); }\n",
    "\n",
    ".btn-estreito { flex: 0 0 auto; }\n",
    ".btn-desconectar { margin-top: 12px; }\n",
    "\n",
    "/* ---------- Chips / filtros ---------- */\n",
    "\n",
    ".filter-row {\n",
    "  display: flex;\n",
    "  gap: 8px;\n",
    "  margin-bottom: 14px;\n",
    "  overflow-x: auto;\n",
    "  scrollbar-width: none;\n",
    "  padding-bottom: 2px;\n",
    "}\n",
    ".filter-row::-webkit-scrollbar { display: none; }\n",
    "\n",
    ".chip {\n",
    "  border: 1.5px solid var(--ivory-deep);\n",
    "  background: var(--paper);\n",
    "  color: var(--ink-soft);\n",
    "  border-radius: 99px;\n",
    "  padding: 7px 15px;\n",
    "  font-size: 0.82rem;\n",
    "  font-weight: 700;\n",
    "  white-space: nowrap;\n",
    "  transition: background 0.2s, color 0.2s, border-color 0.2s;\n",
    "}\n",
    ".chip.is-active {\n",
    "  background: var(--ink);\n",
    "  color: var(--ivory);\n",
    "  border-color: var(--ink);\n",
    "}\n",
    "\n",
    "/* ---------- Listas ---------- */\n",
    "\n",
    ".item-list, .pair-list { list-style: none; display: flex; flex-direction: column; gap: 10px; }\n",
    "\n",
    ".list-item {\n",
    "  background: var(--paper);\n",
    "  border: 1px solid rgba(179, 137, 46, 0.18);\n",
    "  border-radius: var(--radius);\n",
    "  padding: 12px 14px;\n",
    "  display: flex;\n",
    "  align-items: center;\n",
    "  gap: 12px;\n",
    "  box-shadow: 0 1px 4px rgba(47, 58, 42, 0.05);\n",
    "  animation: itemIn 0.25s ease both;\n",
    "}\n",
    "\n",
    "@keyframes itemIn {\n",
    "  from { opacity: 0; transform: translateY(6px); }\n",
    "  to { opacity: 1; transform: none; }\n",
    "}\n",
    "\n",
    ".list-item .item-main { flex: 1; min-width: 0; }\n",
    "\n",
    ".item-title {\n",
    "  font-weight: 700;\n",
    "  font-size: 0.98rem;\n",
    "  overflow: hidden;\n",
    "  text-overflow: ellipsis;\n",
    "  white-space: nowrap;\n",
    "}\n",
    "\n",
    ".item-meta { font-size: 0.78rem; color: var(--ink-faint); display: flex; gap: 8px; flex-wrap: wrap; }\n",
    "\n",
    ".item-valor {\n",
    "  font-weight: 800;\n",
    "  font-size: 0.92rem;\n",
    "  font-variant-numeric: tabular-nums;\n",
    "  white-space: nowrap;\n",
    "  color: var(--ink-soft);\n",
    "}\n",
    "\n",
    ".list-item.is-done .item-title { text-decoration: line-through; color: var(--ink-faint); }\n",
    ".list-item.is-done { background: var(--sage-soft); border-color: rgba(125, 144, 112, 0.4); }\n",
    ".list-item.is-done .item-valor { color: var(--ok); }\n",
    "\n",
    ".badge {\n",
    "  font-size: 0.68rem;\n",
    "  font-weight: 800;\n",
    "  text-transform: uppercase;\n",
    "  letter-spacing: 0.08em;\n",
    "  border-radius: 99px;\n",
    "  padding: 3px 9px;\n",
    "}\n",
    ".badge-noiva { background: var(--rose-soft); color: #a05b50; }\n",
    ".badge-noivo { background: var(--sage-soft); color: #55704a; }\n",
    ".badge-cat { background: var(--ivory-deep); color: var(--ink-soft); }\n",
    "\n",
    ".check-toggle {\n",
    "  width: 28px;\n",
    "  height: 28px;\n",
    "  border-radius: 50%;\n",
    "  border: 2px solid var(--gold-soft);\n",
    "  background: var(--paper);\n",
    "  flex-shrink: 0;\n",
    "  display: grid;\n",
    "  place-items: center;\n",
    "  color: transparent;\n",
    "  transition: background 0.2s, color 0.2s, border-color 0.2s;\n",
    "}\n",
    ".check-toggle.is-on {\n",
    "  background: var(--ok);\n",
    "  border-color: var(--ok);\n",
    "  color: var(--paper);\n",
    "}\n",
    "\n",
    ".btn-remove {\n",
    "  background: none;\n",
    "  border: none;\n",
    "  color: var(--ink-faint);\n",
    "  padding: 6px;\n",
    "  border-radius: 10px;\n",
    "  flex-shrink: 0;\n",
    "  display: grid;\n",
    "  place-items: center;\n",
    "  transition: color 0.2s, background 0.2s;\n",
    "}\n",
    ".btn-remove:hover { color: var(--danger); background: var(--rose-soft); }\n",
    "\n",
    ".link-contato {\n",
    "  color: var(--gold);\n",
    "  font-weight: 700;\n",
    "  text-decoration: none;\n",
    "  font-size: 0.82rem;\n",
    "}\n",
    "\n",
    "/* ---------- Padrinhos ---------- */\n",
    "\n",
    ".pair-item {\n",
    "  background: var(--paper);\n",
    "  border: 1px solid rgba(179, 137, 46, 0.18);\n",
    "  border-radius: var(--radius);\n",
    "  padding: 14px 16px;\n",
    "  display: flex;\n",
    "  align-items: center;\n",
    "  gap: 12px;\n",
    "  box-shadow: 0 1px 4px rgba(47, 58, 42, 0.05);\n",
    "  animation: itemIn 0.25s ease both;\n",
    "}\n",
    "\n",
    ".pair-num {\n",
    "  font-family: var(--font-display);\n",
    "  font-style: italic;\n",
    "  color: var(--gold);\n",
    "  font-size: 1.1rem;\n",
    "  width: 26px;\n",
    "  text-align: center;\n",
    "  flex-shrink: 0;\n",
    "}\n",
    "\n",
    ".pair-names { flex: 1; min-width: 0; display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }\n",
    ".pair-names .nome { font-weight: 700; font-size: 0.95rem; }\n",
    ".pair-names .amp { font-size: 1.05rem; }\n",
    "\n",
    "/* ---------- Empty state / toast ---------- */\n",
    "\n",
    ".empty-state {\n",
    "  text-align: center;\n",
    "  color: var(--ink-faint);\n",
    "  font-size: 0.9rem;\n",
    "  padding: 34px 20px;\n",
    "  font-style: italic;\n",
    "  font-family: var(--font-display);\n",
    "  display: none;\n",
    "}\n",
    ".empty-state.is-visible { display: block; }\n",
    "\n",
    ".toast {\n",
    "  position: fixed;\n",
    "  left: 50%;\n",
    "  bottom: calc(var(--nav-h) + 18px + env(safe-area-inset-bottom, 0px));\n",
    "  transform: translateX(-50%) translateY(20px);\n",
    "  background: var(--ink);\n",
    "  color: var(--ivory);\n",
    "  border-radius: 99px;\n",
    "  padding: 10px 22px;\n",
    "  font-size: 0.86rem;\n",
    "  font-weight: 700;\n",
    "  box-shadow: var(--shadow);\n",
    "  opacity: 0;\n",
    "  pointer-events: none;\n",
    "  transition: opacity 0.25s, transform 0.25s;\n",
    "  z-index: 60;\n",
    "  max-width: 90vw;\n",
    "  text-align: center;\n",
    "}\n",
    ".toast.is-visible { opacity: 1; transform: translateX(-50%) translateY(0); }\n",
    "\n",
    "/* ---------- Bottom nav ---------- */\n",
    "\n",
    ".bottom-nav {\n",
    "  position: fixed;\n",
    "  bottom: 0;\n",
    "  left: 0;\n",
    "  right: 0;\n",
    "  z-index: 30;\n",
    "  background: rgba(255, 253, 248, 0.92);\n",
    "  backdrop-filter: blur(12px);\n",
    "  -webkit-backdrop-filter: blur(12px);\n",
    "  border-top: 1px solid rgba(179, 137, 46, 0.25);\n",
    "  display: flex;\n",
    "  justify-content: space-around;\n",
    "  padding: 6px 4px calc(6px + env(safe-area-inset-bottom, 0px));\n",
    "}\n",
    "\n",
    ".nav-item {\n",
    "  background: none;\n",
    "  border: none;\n",
    "  color: var(--ink-faint);\n",
    "  display: flex;\n",
    "  flex-direction: column;\n",
    "  align-items: center;\n",
    "  gap: 3px;\n",
    "  font-size: 0.64rem;\n",
    "  font-weight: 700;\n",
    "  letter-spacing: 0.04em;\n",
    "  padding: 5px 10px;\n",
    "  border-radius: 12px;\n",
    "  transition: color 0.2s;\n",
    "  flex: 1;\n",
    "  max-width: 96px;\n",
    "}\n",
    ".nav-item.is-active { color: var(--ink); }\n",
    ".nav-item.is-active svg { color: var(--gold); }\n",
    "\n",
    "@media (min-width: 560px) {\n",
    "  .stat-grid { grid-template-columns: repeat(4, 1fr); }\n",
    "  .cd-unit { min-width: 84px; }\n",
    "}\n",
    ""
  ].join(""),
  },
  "/js/app.js": {
    type: "text/javascript; charset=utf-8",
    body: [
    "/* ============================================================\n",
    "   Nosso Casamento — lógica do app\n",
    "   Dados salvos em localStorage (apenas neste aparelho).\n",
    "   ============================================================ */\n",
    "\n",
    "(() => {\n",
    "  \"use strict\";\n",
    "\n",
    "  const STORAGE_KEY = \"nosso-casamento-v1\";\n",
    "  const CASAL_KEY = \"nosso-casamento-casal\";\n",
    "\n",
    "  // Quando o app é servido pela Edge Function do Supabase, a API de\n",
    "  // sincronização vive no mesmo caminho, em ./api\n",
    "  const API_URL = location.pathname.replace(/\\/$/, \"\") + \"/api\";\n",
    "\n",
    "  const estadoInicial = () => ({\n",
    "    config: { noiva: \"\", noivo: \"\", data: \"\", local: \"\" },\n",
    "    convidados: [],   // { id, nome, lado: \"noiva\"|\"noivo\", acompanhantes, confirmado }\n",
    "    itens: [],        // { id, descricao, valor (centavos), resolvido }\n",
    "    padrinhos: [],    // { id, padrinho, madrinha }\n",
    "    fornecedores: [], // { id, nome, categoria, contato }\n",
    "  });\n",
    "\n",
    "  let state = carregar();\n",
    "  let filtroConvidados = \"todos\";\n",
    "  let filtroChecklist = \"todos\";\n",
    "\n",
    "  /* ---------- persistência ---------- */\n",
    "\n",
    "  function carregar() {\n",
    "    try {\n",
    "      const raw = localStorage.getItem(STORAGE_KEY);\n",
    "      if (!raw) return estadoInicial();\n",
    "      const dados = JSON.parse(raw);\n",
    "      return { ...estadoInicial(), ...dados, config: { ...estadoInicial().config, ...dados.config } };\n",
    "    } catch {\n",
    "      return estadoInicial();\n",
    "    }\n",
    "  }\n",
    "\n",
    "  function salvar() {\n",
    "    try {\n",
    "      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));\n",
    "    } catch {\n",
    "      toast(\"Não foi possível salvar os dados 😢\");\n",
    "    }\n",
    "    agendarEnvio();\n",
    "  }\n",
    "\n",
    "  const uid = () => Math.random().toString(36).slice(2, 9) + Date.now().toString(36);\n",
    "\n",
    "  /* ---------- helpers ---------- */\n",
    "\n",
    "  const $ = (sel) => document.querySelector(sel);\n",
    "  const $$ = (sel) => Array.from(document.querySelectorAll(sel));\n",
    "\n",
    "  const fmtBRL = new Intl.NumberFormat(\"pt-BR\", { style: \"currency\", currency: \"BRL\" });\n",
    "  const brl = (centavos) => fmtBRL.format((centavos || 0) / 100);\n",
    "\n",
    "  function parseValor(texto) {\n",
    "    // aceita \"1.234,56\", \"1234.56\", \"1234\", \"R$ 50\"\n",
    "    const limpo = String(texto).replace(/[^\\d.,-]/g, \"\").trim();\n",
    "    if (!limpo) return 0;\n",
    "    let normalizado = limpo;\n",
    "    if (limpo.includes(\",\")) {\n",
    "      normalizado = limpo.replace(/\\./g, \"\").replace(\",\", \".\");\n",
    "    }\n",
    "    const n = parseFloat(normalizado);\n",
    "    return Number.isFinite(n) && n >= 0 ? Math.round(n * 100) : 0;\n",
    "  }\n",
    "\n",
    "  function escapeHtml(texto) {\n",
    "    const div = document.createElement(\"div\");\n",
    "    div.textContent = texto;\n",
    "    return div.innerHTML;\n",
    "  }\n",
    "\n",
    "  let toastTimer;\n",
    "  function toast(msg) {\n",
    "    const el = $(\"#toast\");\n",
    "    el.textContent = msg;\n",
    "    el.classList.add(\"is-visible\");\n",
    "    clearTimeout(toastTimer);\n",
    "    toastTimer = setTimeout(() => el.classList.remove(\"is-visible\"), 2400);\n",
    "  }\n",
    "\n",
    "  const nomeNoiva = () => state.config.noiva.trim() || \"Noiva\";\n",
    "  const nomeNoivo = () => state.config.noivo.trim() || \"Noivo\";\n",
    "\n",
    "  const totalPessoas = (c) => 1 + (c.acompanhantes || 0);\n",
    "\n",
    "  const iconeLixeira =\n",
    "    '<svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 7h16M9 7V5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2m3 0-.8 12.1a2 2 0 0 1-2 1.9H8.8a2 2 0 0 1-2-1.9L6 7\"/><path d=\"M10 11v6M14 11v6\"/></svg>';\n",
    "  const iconeCheck =\n",
    "    '<svg viewBox=\"0 0 24 24\" width=\"15\" height=\"15\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m5 13 4 4 10-10\"/></svg>';\n",
    "\n",
    "  /* ---------- navegação ---------- */\n",
    "\n",
    "  function irPara(view) {\n",
    "    $$(\".view\").forEach((v) => v.classList.remove(\"is-active\"));\n",
    "    const alvo = $(\"#view-\" + view);\n",
    "    if (alvo) alvo.classList.add(\"is-active\");\n",
    "    $$(\".nav-item\").forEach((b) => b.classList.toggle(\"is-active\", b.dataset.view === view));\n",
    "    window.scrollTo({ top: 0, behavior: \"instant\" });\n",
    "  }\n",
    "\n",
    "  $$(\".nav-item\").forEach((btn) => btn.addEventListener(\"click\", () => irPara(btn.dataset.view)));\n",
    "  $$(\"[data-goto]\").forEach((btn) => btn.addEventListener(\"click\", () => irPara(btn.dataset.goto)));\n",
    "  $(\"#btn-config\").addEventListener(\"click\", () => irPara(\"config\"));\n",
    "\n",
    "  /* ---------- contagem regressiva ---------- */\n",
    "\n",
    "  function atualizarContagem() {\n",
    "    const cfg = state.config;\n",
    "    const cartao = $(\".countdown-card\");\n",
    "    if (!cfg.data) {\n",
    "      [\"dias\", \"horas\", \"min\", \"seg\"].forEach((u) => ($(\"#cd-\" + u).textContent = \"--\"));\n",
    "      $(\"#countdown-date\").textContent = \"Toque na engrenagem para configurar a data 💍\";\n",
    "      $(\".countdown-label\").textContent = \"Faltam\";\n",
    "      cartao.classList.remove(\"is-past\");\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    const alvo = new Date(cfg.data);\n",
    "    const agora = new Date();\n",
    "    let diff = alvo - agora;\n",
    "\n",
    "    const dataFmt = alvo.toLocaleDateString(\"pt-BR\", {\n",
    "      weekday: \"long\", day: \"numeric\", month: \"long\", year: \"numeric\",\n",
    "    });\n",
    "    const horaFmt = alvo.toLocaleTimeString(\"pt-BR\", { hour: \"2-digit\", minute: \"2-digit\" });\n",
    "    const local = cfg.local.trim() ? \" · \" + cfg.local.trim() : \"\";\n",
    "    $(\"#countdown-date\").textContent = `${dataFmt}, às ${horaFmt}${local}`;\n",
    "\n",
    "    if (diff <= 0) {\n",
    "      cartao.classList.add(\"is-past\");\n",
    "      $(\".countdown-label\").textContent = diff > -864e5 ? \"É hoje! 🎉\" : \"Felizes para sempre 💛\";\n",
    "      [\"dias\", \"horas\", \"min\", \"seg\"].forEach((u) => ($(\"#cd-\" + u).textContent = \"0\"));\n",
    "      return;\n",
    "    }\n",
    "\n",
    "    cartao.classList.remove(\"is-past\");\n",
    "    $(\".countdown-label\").textContent = \"Faltam\";\n",
    "    const dias = Math.floor(diff / 864e5);\n",
    "    diff -= dias * 864e5;\n",
    "    const horas = Math.floor(diff / 36e5);\n",
    "    diff -= horas * 36e5;\n",
    "    const min = Math.floor(diff / 6e4);\n",
    "    diff -= min * 6e4;\n",
    "    const seg = Math.floor(diff / 1e3);\n",
    "\n",
    "    $(\"#cd-dias\").textContent = String(dias);\n",
    "    $(\"#cd-horas\").textContent = String(horas).padStart(2, \"0\");\n",
    "    $(\"#cd-min\").textContent = String(min).padStart(2, \"0\");\n",
    "    $(\"#cd-seg\").textContent = String(seg).padStart(2, \"0\");\n",
    "  }\n",
    "\n",
    "  setInterval(atualizarContagem, 1000);\n",
    "\n",
    "  /* ---------- cabeçalho ---------- */\n",
    "\n",
    "  function renderHeader() {\n",
    "    const { noiva, noivo, data } = state.config;\n",
    "    const temNomes = noiva.trim() || noivo.trim();\n",
    "    $(\"#header-couple\").textContent = temNomes ? `${nomeNoiva()} & ${nomeNoivo()}` : \"Nosso Casamento\";\n",
    "    $(\"#monogram\").textContent = temNomes\n",
    "      ? `${nomeNoiva()[0].toUpperCase()}&${nomeNoivo()[0].toUpperCase()}`\n",
    "      : \"N&N\";\n",
    "    $(\"#header-date\").textContent = data\n",
    "      ? new Date(data).toLocaleDateString(\"pt-BR\", { day: \"2-digit\", month: \"long\", year: \"numeric\" })\n",
    "      : \"Configure a data do grande dia\";\n",
    "\n",
    "    // rótulos dos lados acompanham os nomes do casal\n",
    "    $(\"#lado-a-label\").textContent = nomeNoiva();\n",
    "    $(\"#lado-b-label\").textContent = nomeNoivo();\n",
    "    $(\"#seg-lado-a\").textContent = nomeNoiva();\n",
    "    $(\"#seg-lado-b\").textContent = nomeNoivo();\n",
    "    $(\"#chip-lado-a\").textContent = nomeNoiva();\n",
    "    $(\"#chip-lado-b\").textContent = nomeNoivo();\n",
    "  }\n",
    "\n",
    "  /* ---------- dashboard ---------- */\n",
    "\n",
    "  function renderDashboard() {\n",
    "    const conv = state.convidados;\n",
    "    const totalConvidados = conv.reduce((s, c) => s + totalPessoas(c), 0);\n",
    "    const confirmados = conv.filter((c) => c.confirmado).reduce((s, c) => s + totalPessoas(c), 0);\n",
    "    const ladoNoiva = conv.filter((c) => c.lado === \"noiva\").reduce((s, c) => s + totalPessoas(c), 0);\n",
    "    const ladoNoivo = conv.filter((c) => c.lado === \"noivo\").reduce((s, c) => s + totalPessoas(c), 0);\n",
    "\n",
    "    $(\"#stat-convidados\").textContent = totalConvidados;\n",
    "    $(\"#stat-convidados-sub\").textContent = `${confirmados} confirmado${confirmados === 1 ? \"\" : \"s\"}`;\n",
    "\n",
    "    const pendentes = state.itens.filter((i) => !i.resolvido);\n",
    "    const valorPendente = pendentes.reduce((s, i) => s + (i.valor || 0), 0);\n",
    "    const valorResolvido = state.itens.filter((i) => i.resolvido).reduce((s, i) => s + (i.valor || 0), 0);\n",
    "    const valorTotal = valorPendente + valorResolvido;\n",
    "\n",
    "    $(\"#stat-pendencias\").textContent = pendentes.length;\n",
    "    $(\"#stat-pendencias-sub\").textContent = valorPendente ? brl(valorPendente) : \"tudo em dia 🎉\";\n",
    "\n",
    "    $(\"#stat-padrinhos\").textContent = state.padrinhos.length * 2;\n",
    "    $(\"#stat-padrinhos-sub\").textContent = `${state.padrinhos.length} par${state.padrinhos.length === 1 ? \"\" : \"es\"}`;\n",
    "\n",
    "    $(\"#stat-fornecedores\").textContent = state.fornecedores.length;\n",
    "    $(\"#stat-fornecedores-sub\").textContent = state.fornecedores.length\n",
    "      ? \"contatos salvos\"\n",
    "      : \"nenhum ainda\";\n",
    "\n",
    "    // orçamento\n",
    "    $(\"#resumo-orcamento-total\").textContent = brl(valorTotal);\n",
    "    $(\"#resumo-valor-resolvido\").textContent = brl(valorResolvido);\n",
    "    $(\"#resumo-valor-pendente\").textContent = brl(valorPendente);\n",
    "    $(\"#orcamento-progress\").style.width = valorTotal ? (valorResolvido / valorTotal) * 100 + \"%\" : \"0%\";\n",
    "\n",
    "    // checklist\n",
    "    const feitos = state.itens.length - pendentes.length;\n",
    "    $(\"#resumo-checklist-frac\").textContent = `${feitos}/${state.itens.length}`;\n",
    "    $(\"#checklist-progress\").style.width = state.itens.length ? (feitos / state.itens.length) * 100 + \"%\" : \"0%\";\n",
    "\n",
    "    const proximos = pendentes.slice(0, 4);\n",
    "    $(\"#dash-pendentes\").innerHTML = proximos.length\n",
    "      ? proximos\n",
    "          .map(\n",
    "            (i) =>\n",
    "              `<li><span>${escapeHtml(i.descricao)}</span>` +\n",
    "              (i.valor ? `<span class=\"mini-valor\">${brl(i.valor)}</span>` : \"\") +\n",
    "              `</li>`\n",
    "          )\n",
    "          .join(\"\")\n",
    "      : `<li><span>Nenhuma pendência — aproveitem o momento 💛</span></li>`;\n",
    "\n",
    "    // lados\n",
    "    $(\"#resumo-lado-a\").textContent = ladoNoiva;\n",
    "    $(\"#resumo-lado-b\").textContent = ladoNoivo;\n",
    "    const somaLados = ladoNoiva + ladoNoivo;\n",
    "    $(\"#split-noiva\").style.width = somaLados ? (ladoNoiva / somaLados) * 100 + \"%\" : \"50%\";\n",
    "    $(\"#split-noivo\").style.width = somaLados ? (ladoNoivo / somaLados) * 100 + \"%\" : \"50%\";\n",
    "  }\n",
    "\n",
    "  /* ---------- convidados ---------- */\n",
    "\n",
    "  function renderConvidados() {\n",
    "    const lista = $(\"#lista-convidados\");\n",
    "    const conv = state.convidados;\n",
    "\n",
    "    const filtrados = conv.filter((c) => {\n",
    "      if (filtroConvidados === \"noiva\") return c.lado === \"noiva\";\n",
    "      if (filtroConvidados === \"noivo\") return c.lado === \"noivo\";\n",
    "      if (filtroConvidados === \"confirmados\") return c.confirmado;\n",
    "      return true;\n",
    "    });\n",
    "\n",
    "    lista.innerHTML = filtrados\n",
    "      .map((c) => {\n",
    "        const pessoas = totalPessoas(c);\n",
    "        const badge =\n",
    "          c.lado === \"noiva\"\n",
    "            ? `<span class=\"badge badge-noiva\">${escapeHtml(nomeNoiva())}</span>`\n",
    "            : `<span class=\"badge badge-noivo\">${escapeHtml(nomeNoivo())}</span>`;\n",
    "        return `<li class=\"list-item ${c.confirmado ? \"is-done\" : \"\"}\" data-id=\"${c.id}\">\n",
    "          <button class=\"check-toggle ${c.confirmado ? \"is-on\" : \"\"}\" data-acao=\"confirmar\" aria-label=\"Confirmar presença\" title=\"Confirmar presença\">${iconeCheck}</button>\n",
    "          <div class=\"item-main\">\n",
    "            <div class=\"item-title\">${escapeHtml(c.nome)}</div>\n",
    "            <div class=\"item-meta\">${badge}<span>${pessoas} pessoa${pessoas === 1 ? \"\" : \"s\"}${c.acompanhantes ? ` (+${c.acompanhantes} acomp.)` : \"\"}</span></div>\n",
    "          </div>\n",
    "          <button class=\"btn-remove\" data-acao=\"remover\" aria-label=\"Remover\">${iconeLixeira}</button>\n",
    "        </li>`;\n",
    "      })\n",
    "      .join(\"\");\n",
    "\n",
    "    $(\"#convidados-empty\").classList.toggle(\"is-visible\", conv.length === 0);\n",
    "\n",
    "    const total = conv.reduce((s, c) => s + totalPessoas(c), 0);\n",
    "    const confirmados = conv.filter((c) => c.confirmado).reduce((s, c) => s + totalPessoas(c), 0);\n",
    "    $(\"#convidados-resumo\").textContent = conv.length\n",
    "      ? `${total} pessoa${total === 1 ? \"\" : \"s\"} no total · ${confirmados} confirmada${confirmados === 1 ? \"\" : \"s\"}`\n",
    "      : \"Nenhum convidado ainda\";\n",
    "  }\n",
    "\n",
    "  $(\"#form-convidado\").addEventListener(\"submit\", (e) => {\n",
    "    e.preventDefault();\n",
    "    const nome = $(\"#convidado-nome\").value.trim();\n",
    "    if (!nome) return;\n",
    "    const lado = document.querySelector('input[name=\"convidado-lado\"]:checked').value;\n",
    "    const acomp = Math.max(0, Math.min(20, parseInt($(\"#convidado-acomp\").value, 10) || 0));\n",
    "    state.convidados.push({ id: uid(), nome, lado, acompanhantes: acomp, confirmado: false });\n",
    "    salvar();\n",
    "    renderTudo();\n",
    "    e.target.reset();\n",
    "    document.querySelector(`input[name=\"convidado-lado\"][value=\"${lado}\"]`).checked = true;\n",
    "    $(\"#convidado-nome\").focus();\n",
    "    toast(`${nome} adicionado 🎉`);\n",
    "  });\n",
    "\n",
    "  $(\"#lista-convidados\").addEventListener(\"click\", (e) => {\n",
    "    const btn = e.target.closest(\"[data-acao]\");\n",
    "    if (!btn) return;\n",
    "    const id = btn.closest(\"[data-id]\").dataset.id;\n",
    "    const c = state.convidados.find((x) => x.id === id);\n",
    "    if (!c) return;\n",
    "    if (btn.dataset.acao === \"confirmar\") {\n",
    "      c.confirmado = !c.confirmado;\n",
    "    } else if (btn.dataset.acao === \"remover\") {\n",
    "      if (!confirm(`Remover ${c.nome} da lista?`)) return;\n",
    "      state.convidados = state.convidados.filter((x) => x.id !== id);\n",
    "    }\n",
    "    salvar();\n",
    "    renderTudo();\n",
    "  });\n",
    "\n",
    "  $(\"#convidados-filtros\").addEventListener(\"click\", (e) => {\n",
    "    const chip = e.target.closest(\".chip\");\n",
    "    if (!chip) return;\n",
    "    filtroConvidados = chip.dataset.filtro;\n",
    "    $$(\"#convidados-filtros .chip\").forEach((c) => c.classList.toggle(\"is-active\", c === chip));\n",
    "    renderConvidados();\n",
    "  });\n",
    "\n",
    "  /* ---------- checklist ---------- */\n",
    "\n",
    "  function renderChecklist() {\n",
    "    const lista = $(\"#lista-itens\");\n",
    "    const itens = state.itens;\n",
    "\n",
    "    const filtrados = itens.filter((i) => {\n",
    "      if (filtroChecklist === \"pendentes\") return !i.resolvido;\n",
    "      if (filtroChecklist === \"resolvidos\") return i.resolvido;\n",
    "      return true;\n",
    "    });\n",
    "\n",
    "    lista.innerHTML = filtrados\n",
    "      .map(\n",
    "        (i) => `<li class=\"list-item ${i.resolvido ? \"is-done\" : \"\"}\" data-id=\"${i.id}\">\n",
    "          <button class=\"check-toggle ${i.resolvido ? \"is-on\" : \"\"}\" data-acao=\"resolver\" aria-label=\"Marcar como resolvido\" title=\"Marcar como resolvido\">${iconeCheck}</button>\n",
    "          <div class=\"item-main\">\n",
    "            <div class=\"item-title\">${escapeHtml(i.descricao)}</div>\n",
    "          </div>\n",
    "          ${i.valor ? `<span class=\"item-valor\">${brl(i.valor)}</span>` : \"\"}\n",
    "          <button class=\"btn-remove\" data-acao=\"remover\" aria-label=\"Remover\">${iconeLixeira}</button>\n",
    "        </li>`\n",
    "      )\n",
    "      .join(\"\");\n",
    "\n",
    "    $(\"#checklist-empty\").classList.toggle(\"is-visible\", itens.length === 0);\n",
    "\n",
    "    const valorTotal = itens.reduce((s, i) => s + (i.valor || 0), 0);\n",
    "    const valorResolvido = itens.filter((i) => i.resolvido).reduce((s, i) => s + (i.valor || 0), 0);\n",
    "    $(\"#total-geral\").textContent = brl(valorTotal);\n",
    "    $(\"#total-resolvido\").textContent = brl(valorResolvido);\n",
    "    $(\"#total-pendente\").textContent = brl(valorTotal - valorResolvido);\n",
    "\n",
    "    const feitos = itens.filter((i) => i.resolvido).length;\n",
    "    $(\"#checklist-resumo\").textContent = itens.length\n",
    "      ? `${feitos} de ${itens.length} resolvido${itens.length === 1 ? \"\" : \"s\"}`\n",
    "      : \"Nenhum item ainda\";\n",
    "  }\n",
    "\n",
    "  $(\"#form-item\").addEventListener(\"submit\", (e) => {\n",
    "    e.preventDefault();\n",
    "    const desc = $(\"#item-desc\").value.trim();\n",
    "    if (!desc) return;\n",
    "    const valor = parseValor($(\"#item-valor\").value);\n",
    "    state.itens.push({ id: uid(), descricao: desc, valor, resolvido: false });\n",
    "    salvar();\n",
    "    renderTudo();\n",
    "    e.target.reset();\n",
    "    $(\"#item-desc\").focus();\n",
    "    toast(\"Item adicionado ✅\");\n",
    "  });\n",
    "\n",
    "  $(\"#lista-itens\").addEventListener(\"click\", (e) => {\n",
    "    const btn = e.target.closest(\"[data-acao]\");\n",
    "    if (!btn) return;\n",
    "    const id = btn.closest(\"[data-id]\").dataset.id;\n",
    "    const item = state.itens.find((x) => x.id === id);\n",
    "    if (!item) return;\n",
    "    if (btn.dataset.acao === \"resolver\") {\n",
    "      item.resolvido = !item.resolvido;\n",
    "      if (item.resolvido) toast(\"Resolvido! 🎉\");\n",
    "    } else if (btn.dataset.acao === \"remover\") {\n",
    "      if (!confirm(`Remover \"${item.descricao}\"?`)) return;\n",
    "      state.itens = state.itens.filter((x) => x.id !== id);\n",
    "    }\n",
    "    salvar();\n",
    "    renderTudo();\n",
    "  });\n",
    "\n",
    "  $(\"#checklist-filtros\").addEventListener(\"click\", (e) => {\n",
    "    const chip = e.target.closest(\".chip\");\n",
    "    if (!chip) return;\n",
    "    filtroChecklist = chip.dataset.filtro;\n",
    "    $$(\"#checklist-filtros .chip\").forEach((c) => c.classList.toggle(\"is-active\", c === chip));\n",
    "    renderChecklist();\n",
    "  });\n",
    "\n",
    "  /* ---------- padrinhos ---------- */\n",
    "\n",
    "  function renderPadrinhos() {\n",
    "    const lista = $(\"#lista-padrinhos\");\n",
    "    lista.innerHTML = state.padrinhos\n",
    "      .map(\n",
    "        (p, idx) => `<li class=\"pair-item\" data-id=\"${p.id}\">\n",
    "          <span class=\"pair-num\">${idx + 1}</span>\n",
    "          <div class=\"pair-names\">\n",
    "            <span class=\"nome\">${escapeHtml(p.padrinho)}</span>\n",
    "            <span class=\"amp\">&amp;</span>\n",
    "            <span class=\"nome\">${escapeHtml(p.madrinha)}</span>\n",
    "          </div>\n",
    "          <button class=\"btn-remove\" data-acao=\"remover\" aria-label=\"Remover par\">${iconeLixeira}</button>\n",
    "        </li>`\n",
    "      )\n",
    "      .join(\"\");\n",
    "\n",
    "    $(\"#padrinhos-empty\").classList.toggle(\"is-visible\", state.padrinhos.length === 0);\n",
    "\n",
    "    const n = state.padrinhos.length;\n",
    "    $(\"#padrinhos-resumo\").textContent = n\n",
    "      ? `${n} par${n === 1 ? \"\" : \"es\"} · ${n * 2} pessoa${n * 2 === 1 ? \"\" : \"s\"}`\n",
    "      : \"Nenhum par ainda\";\n",
    "  }\n",
    "\n",
    "  $(\"#form-padrinho\").addEventListener(\"submit\", (e) => {\n",
    "    e.preventDefault();\n",
    "    const padrinho = $(\"#padrinho-nome\").value.trim();\n",
    "    const madrinha = $(\"#madrinha-nome\").value.trim();\n",
    "    if (!padrinho || !madrinha) return;\n",
    "    state.padrinhos.push({ id: uid(), padrinho, madrinha });\n",
    "    salvar();\n",
    "    renderTudo();\n",
    "    e.target.reset();\n",
    "    $(\"#padrinho-nome\").focus();\n",
    "    toast(\"Par adicionado 💛\");\n",
    "  });\n",
    "\n",
    "  $(\"#lista-padrinhos\").addEventListener(\"click\", (e) => {\n",
    "    const btn = e.target.closest(\"[data-acao]\");\n",
    "    if (!btn) return;\n",
    "    const id = btn.closest(\"[data-id]\").dataset.id;\n",
    "    const p = state.padrinhos.find((x) => x.id === id);\n",
    "    if (!p) return;\n",
    "    if (!confirm(`Remover ${p.padrinho} & ${p.madrinha}?`)) return;\n",
    "    state.padrinhos = state.padrinhos.filter((x) => x.id !== id);\n",
    "    salvar();\n",
    "    renderTudo();\n",
    "  });\n",
    "\n",
    "  /* ---------- fornecedores ---------- */\n",
    "\n",
    "  function renderFornecedores() {\n",
    "    const lista = $(\"#lista-fornecedores\");\n",
    "    lista.innerHTML = state.fornecedores\n",
    "      .map((f) => {\n",
    "        const tel = (f.contato || \"\").replace(/\\D/g, \"\");\n",
    "        const linkContato = tel\n",
    "          ? `<a class=\"link-contato\" href=\"https://wa.me/55${tel}\" target=\"_blank\" rel=\"noopener\">WhatsApp: ${escapeHtml(f.contato)}</a>`\n",
    "          : \"\";\n",
    "        return `<li class=\"list-item\" data-id=\"${f.id}\">\n",
    "          <div class=\"item-main\">\n",
    "            <div class=\"item-title\">${escapeHtml(f.nome)}</div>\n",
    "            <div class=\"item-meta\"><span class=\"badge badge-cat\">${escapeHtml(f.categoria)}</span>${linkContato}</div>\n",
    "          </div>\n",
    "          <button class=\"btn-remove\" data-acao=\"remover\" aria-label=\"Remover\">${iconeLixeira}</button>\n",
    "        </li>`;\n",
    "      })\n",
    "      .join(\"\");\n",
    "\n",
    "    $(\"#fornecedores-empty\").classList.toggle(\"is-visible\", state.fornecedores.length === 0);\n",
    "\n",
    "    const n = state.fornecedores.length;\n",
    "    $(\"#fornecedores-resumo\").textContent = n\n",
    "      ? `${n} fornecedor${n === 1 ? \"\" : \"es\"} cadastrado${n === 1 ? \"\" : \"s\"}`\n",
    "      : \"Nenhum fornecedor ainda\";\n",
    "  }\n",
    "\n",
    "  $(\"#form-fornecedor\").addEventListener(\"submit\", (e) => {\n",
    "    e.preventDefault();\n",
    "    const nome = $(\"#fornecedor-nome\").value.trim();\n",
    "    if (!nome) return;\n",
    "    state.fornecedores.push({\n",
    "      id: uid(),\n",
    "      nome,\n",
    "      categoria: $(\"#fornecedor-categoria\").value,\n",
    "      contato: $(\"#fornecedor-contato\").value.trim(),\n",
    "    });\n",
    "    salvar();\n",
    "    renderTudo();\n",
    "    e.target.reset();\n",
    "    $(\"#fornecedor-nome\").focus();\n",
    "    toast(\"Fornecedor adicionado 📇\");\n",
    "  });\n",
    "\n",
    "  $(\"#lista-fornecedores\").addEventListener(\"click\", (e) => {\n",
    "    const btn = e.target.closest(\"[data-acao]\");\n",
    "    if (!btn) return;\n",
    "    const id = btn.closest(\"[data-id]\").dataset.id;\n",
    "    const f = state.fornecedores.find((x) => x.id === id);\n",
    "    if (!f) return;\n",
    "    if (!confirm(`Remover ${f.nome}?`)) return;\n",
    "    state.fornecedores = state.fornecedores.filter((x) => x.id !== id);\n",
    "    salvar();\n",
    "    renderTudo();\n",
    "  });\n",
    "\n",
    "  /* ---------- configurações ---------- */\n",
    "\n",
    "  function preencherConfig() {\n",
    "    $(\"#config-noiva\").value = state.config.noiva;\n",
    "    $(\"#config-noivo\").value = state.config.noivo;\n",
    "    $(\"#config-data\").value = state.config.data;\n",
    "    $(\"#config-local\").value = state.config.local;\n",
    "  }\n",
    "\n",
    "  $(\"#form-config\").addEventListener(\"submit\", (e) => {\n",
    "    e.preventDefault();\n",
    "    state.config.noiva = $(\"#config-noiva\").value.trim();\n",
    "    state.config.noivo = $(\"#config-noivo\").value.trim();\n",
    "    state.config.data = $(\"#config-data\").value;\n",
    "    state.config.local = $(\"#config-local\").value.trim();\n",
    "    salvar();\n",
    "    renderTudo();\n",
    "    toast(\"Configurações salvas 💾\");\n",
    "    irPara(\"dashboard\");\n",
    "  });\n",
    "\n",
    "  $(\"#btn-exportar\").addEventListener(\"click\", () => {\n",
    "    const blob = new Blob([JSON.stringify(state, null, 2)], { type: \"application/json\" });\n",
    "    const url = URL.createObjectURL(blob);\n",
    "    const a = document.createElement(\"a\");\n",
    "    const hoje = new Date().toISOString().slice(0, 10);\n",
    "    a.href = url;\n",
    "    a.download = `casamento-backup-${hoje}.json`;\n",
    "    a.click();\n",
    "    URL.revokeObjectURL(url);\n",
    "    toast(\"Backup exportado 📦\");\n",
    "  });\n",
    "\n",
    "  $(\"#btn-importar\").addEventListener(\"click\", () => $(\"#input-importar\").click());\n",
    "\n",
    "  $(\"#input-importar\").addEventListener(\"change\", (e) => {\n",
    "    const arquivo = e.target.files[0];\n",
    "    if (!arquivo) return;\n",
    "    const leitor = new FileReader();\n",
    "    leitor.onload = () => {\n",
    "      try {\n",
    "        const dados = JSON.parse(leitor.result);\n",
    "        if (!dados || typeof dados !== \"object\" || !(\"config\" in dados)) {\n",
    "          throw new Error(\"formato inválido\");\n",
    "        }\n",
    "        if (!confirm(\"Importar este backup? Os dados atuais serão substituídos.\")) return;\n",
    "        state = { ...estadoInicial(), ...dados, config: { ...estadoInicial().config, ...dados.config } };\n",
    "        salvar();\n",
    "        preencherConfig();\n",
    "        renderTudo();\n",
    "        toast(\"Backup importado ✅\");\n",
    "      } catch {\n",
    "        toast(\"Arquivo de backup inválido 😢\");\n",
    "      }\n",
    "      e.target.value = \"\";\n",
    "    };\n",
    "    leitor.readAsText(arquivo);\n",
    "  });\n",
    "\n",
    "  $(\"#btn-limpar\").addEventListener(\"click\", () => {\n",
    "    if (!confirm(\"Apagar TODOS os dados deste aparelho? Essa ação não pode ser desfeita.\")) return;\n",
    "    if (!confirm(\"Tem certeza mesmo? Considere exportar um backup antes.\")) return;\n",
    "    state = estadoInicial();\n",
    "    salvar();\n",
    "    preencherConfig();\n",
    "    renderTudo();\n",
    "    toast(\"Dados apagados\");\n",
    "  });\n",
    "\n",
    "  /* ---------- sincronização entre celulares (Supabase) ---------- */\n",
    "\n",
    "  let casal = \"\";\n",
    "  try { casal = localStorage.getItem(CASAL_KEY) || \"\"; } catch {}\n",
    "  let syncTimer;\n",
    "  let syncPendente = false;\n",
    "\n",
    "  async function api(corpo) {\n",
    "    const resp = await fetch(API_URL, {\n",
    "      method: \"POST\",\n",
    "      headers: { \"Content-Type\": \"application/json\" },\n",
    "      body: JSON.stringify(corpo),\n",
    "    });\n",
    "    if (!resp.ok) {\n",
    "      const erro = new Error(\"HTTP \" + resp.status);\n",
    "      erro.status = resp.status;\n",
    "      throw erro;\n",
    "    }\n",
    "    return resp.json();\n",
    "  }\n",
    "\n",
    "  function agendarEnvio() {\n",
    "    if (!casal) return;\n",
    "    clearTimeout(syncTimer);\n",
    "    syncTimer = setTimeout(enviarAgora, 1200);\n",
    "  }\n",
    "\n",
    "  async function enviarAgora() {\n",
    "    if (!casal) return;\n",
    "    clearTimeout(syncTimer);\n",
    "    try {\n",
    "      await api({ op: \"salvar\", casal, estado: state });\n",
    "      syncPendente = false;\n",
    "    } catch {\n",
    "      syncPendente = true;\n",
    "    }\n",
    "    renderSync();\n",
    "  }\n",
    "\n",
    "  function guardarCasal(codigo) {\n",
    "    casal = codigo;\n",
    "    try {\n",
    "      if (codigo) localStorage.setItem(CASAL_KEY, codigo);\n",
    "      else localStorage.removeItem(CASAL_KEY);\n",
    "    } catch {}\n",
    "    renderSync();\n",
    "  }\n",
    "\n",
    "  function renderSync() {\n",
    "    const ligado = Boolean(casal);\n",
    "    $(\"#sync-off\").hidden = ligado;\n",
    "    $(\"#sync-on\").hidden = !ligado;\n",
    "    const status = $(\"#sync-status\");\n",
    "    if (!ligado) {\n",
    "      status.textContent = \"\";\n",
    "    } else if (syncPendente) {\n",
    "      status.textContent = \"aguardando conexão\";\n",
    "      status.className = \"sync-status is-erro\";\n",
    "    } else {\n",
    "      status.textContent = \"sincronizado ✓\";\n",
    "      status.className = \"sync-status is-ok\";\n",
    "    }\n",
    "    if (ligado) $(\"#sync-codigo\").value = casal;\n",
    "  }\n",
    "\n",
    "  $(\"#btn-sync-ativar\").addEventListener(\"click\", async () => {\n",
    "    const btn = $(\"#btn-sync-ativar\");\n",
    "    btn.disabled = true;\n",
    "    try {\n",
    "      const r = await api({ op: \"criar\", estado: state });\n",
    "      guardarCasal(r.casal);\n",
    "      toast(\"Sincronização ativada! Compartilhe o código com seu par 💛\");\n",
    "    } catch {\n",
    "      toast(\"Não foi possível ativar agora. Tente de novo em instantes.\");\n",
    "    }\n",
    "    btn.disabled = false;\n",
    "  });\n",
    "\n",
    "  $(\"#btn-sync-conectar\").addEventListener(\"click\", async () => {\n",
    "    const codigo = $(\"#sync-codigo-entrada\").value.trim();\n",
    "    if (!codigo) {\n",
    "      toast(\"Cole o código do casal primeiro\");\n",
    "      return;\n",
    "    }\n",
    "    try {\n",
    "      const r = await api({ op: \"estado\", casal: codigo });\n",
    "      const temDadosLocais = state.convidados.length || state.itens.length || state.padrinhos.length;\n",
    "      if (temDadosLocais && !confirm(\"Conectar substitui os dados deste aparelho pelos da nuvem. Continuar?\")) return;\n",
    "      state = { ...estadoInicial(), ...r.estado, config: { ...estadoInicial().config, ...(r.estado.config || {}) } };\n",
    "      guardarCasal(codigo);\n",
    "      try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch {}\n",
    "      preencherConfig();\n",
    "      renderTudo();\n",
    "      $(\"#sync-codigo-entrada\").value = \"\";\n",
    "      toast(\"Conectado! Os dados agora ficam em sincronia ✨\");\n",
    "    } catch (e) {\n",
    "      toast(e.status === 404 ? \"Código não encontrado. Confira e tente de novo.\" : \"Não foi possível conectar agora.\");\n",
    "    }\n",
    "  });\n",
    "\n",
    "  $(\"#btn-sync-copiar\").addEventListener(\"click\", async () => {\n",
    "    const campo = $(\"#sync-codigo\");\n",
    "    campo.select();\n",
    "    try {\n",
    "      await navigator.clipboard.writeText(casal);\n",
    "      toast(\"Código copiado 📋\");\n",
    "    } catch {\n",
    "      toast(\"Selecione o código e copie manualmente\");\n",
    "    }\n",
    "  });\n",
    "\n",
    "  $(\"#btn-sync-sair\").addEventListener(\"click\", () => {\n",
    "    if (!confirm(\"Desconectar este aparelho? Os dados continuam aqui e na nuvem, mas param de sincronizar.\")) return;\n",
    "    guardarCasal(\"\");\n",
    "    toast(\"Aparelho desconectado\");\n",
    "  });\n",
    "\n",
    "  async function baixarDaNuvem() {\n",
    "    if (!casal) return;\n",
    "    try {\n",
    "      const r = await api({ op: \"estado\", casal });\n",
    "      state = { ...estadoInicial(), ...r.estado, config: { ...estadoInicial().config, ...(r.estado.config || {}) } };\n",
    "      try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch {}\n",
    "      syncPendente = false;\n",
    "      preencherConfig();\n",
    "      renderTudo();\n",
    "    } catch (e) {\n",
    "      if (e.status === 404) {\n",
    "        // código apagado no servidor: mantém os dados locais e desconecta\n",
    "        guardarCasal(\"\");\n",
    "        toast(\"O código do casal não existe mais; sincronização desativada.\");\n",
    "      } else {\n",
    "        syncPendente = true;\n",
    "      }\n",
    "    }\n",
    "    renderSync();\n",
    "  }\n",
    "\n",
    "  window.addEventListener(\"online\", enviarAgora);\n",
    "  document.addEventListener(\"visibilitychange\", () => {\n",
    "    // envia imediatamente o que estiver pendente ao sair do app\n",
    "    if (document.visibilityState === \"hidden\" && casal && (syncTimer || syncPendente)) {\n",
    "      clearTimeout(syncTimer);\n",
    "      try {\n",
    "        navigator.sendBeacon(\n",
    "          API_URL,\n",
    "          new Blob([JSON.stringify({ op: \"salvar\", casal, estado: state })], { type: \"application/json\" })\n",
    "        );\n",
    "      } catch {}\n",
    "    }\n",
    "  });\n",
    "\n",
    "  /* ---------- render geral ---------- */\n",
    "\n",
    "  function renderTudo() {\n",
    "    renderHeader();\n",
    "    renderDashboard();\n",
    "    renderConvidados();\n",
    "    renderChecklist();\n",
    "    renderPadrinhos();\n",
    "    renderFornecedores();\n",
    "    atualizarContagem();\n",
    "  }\n",
    "\n",
    "  preencherConfig();\n",
    "  renderTudo();\n",
    "  renderSync();\n",
    "  baixarDaNuvem();\n",
    "\n",
    "  // primeira visita: leva direto para a configuração\n",
    "  const primeiraVez = !state.config.data && state.convidados.length === 0 && state.itens.length === 0;\n",
    "  if (primeiraVez) irPara(\"config\");\n",
    "\n",
    "  /* ---------- service worker ---------- */\n",
    "\n",
    "  if (\"serviceWorker\" in navigator) {\n",
    "    window.addEventListener(\"load\", () => {\n",
    "      navigator.serviceWorker.register(\"sw.js\").catch(() => {});\n",
    "    });\n",
    "  }\n",
    "})();\n",
    ""
  ].join(""),
  },
  "/sw.js": {
    type: "text/javascript; charset=utf-8",
    body: [
    "/* Service worker — Nosso Casamento\n",
    "   Estratégia: cache-first para o app shell, com atualização em segundo plano. */\n",
    "\n",
    "const CACHE = \"nosso-casamento-v2\";\n",
    "\n",
    "const SHELL = [\n",
    "  \"./\",\n",
    "  \"./index.html\",\n",
    "  \"./css/styles.css\",\n",
    "  \"./js/app.js\",\n",
    "  \"./manifest.webmanifest\",\n",
    "  \"./icons/icon.svg\",\n",
    "  \"./icons/icon-192.png\",\n",
    "  \"./icons/icon-512.png\",\n",
    "  \"./icons/icon-maskable-512.png\",\n",
    "];\n",
    "\n",
    "self.addEventListener(\"install\", (event) => {\n",
    "  event.waitUntil(\n",
    "    caches\n",
    "      .open(CACHE)\n",
    "      // um arquivo indisponível não pode impedir o app de funcionar offline\n",
    "      .then((cache) => Promise.allSettled(SHELL.map((url) => cache.add(url))))\n",
    "      .then(() => self.skipWaiting())\n",
    "  );\n",
    "});\n",
    "\n",
    "self.addEventListener(\"activate\", (event) => {\n",
    "  event.waitUntil(\n",
    "    caches\n",
    "      .keys()\n",
    "      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))\n",
    "      .then(() => self.clients.claim())\n",
    "  );\n",
    "});\n",
    "\n",
    "self.addEventListener(\"fetch\", (event) => {\n",
    "  const { request } = event;\n",
    "  if (request.method !== \"GET\") return;\n",
    "\n",
    "  const url = new URL(request.url);\n",
    "\n",
    "  // a API de sincronização nunca passa pelo cache\n",
    "  if (url.pathname.endsWith(\"/api\")) return;\n",
    "\n",
    "  // fontes do Google: cache-first com preenchimento dinâmico\n",
    "  if (url.hostname === \"fonts.googleapis.com\" || url.hostname === \"fonts.gstatic.com\") {\n",
    "    event.respondWith(\n",
    "      caches.match(request).then(\n",
    "        (hit) =>\n",
    "          hit ||\n",
    "          fetch(request).then((resp) => {\n",
    "            const clone = resp.clone();\n",
    "            caches.open(CACHE).then((cache) => cache.put(request, clone));\n",
    "            return resp;\n",
    "          })\n",
    "      )\n",
    "    );\n",
    "    return;\n",
    "  }\n",
    "\n",
    "  if (url.origin !== self.location.origin) return;\n",
    "\n",
    "  // app shell: cache-first, atualizando o cache em segundo plano\n",
    "  event.respondWith(\n",
    "    caches.match(request).then((hit) => {\n",
    "      const rede = fetch(request)\n",
    "        .then((resp) => {\n",
    "          if (resp && resp.ok) {\n",
    "            const clone = resp.clone();\n",
    "            caches.open(CACHE).then((cache) => cache.put(request, clone));\n",
    "          }\n",
    "          return resp;\n",
    "        })\n",
    "        .catch(() => hit);\n",
    "      return hit || rede;\n",
    "    })\n",
    "  );\n",
    "});\n",
    ""
  ].join(""),
  },
  "/manifest.webmanifest": {
    type: "application/manifest+json; charset=utf-8",
    body: [
    "{\n",
    "  \"name\": \"Nosso Casamento\",\n",
    "  \"short_name\": \"Casamento\",\n",
    "  \"description\": \"Planejador de casamento: convidados, checklist com custos, padrinhos, fornecedores e contagem regressiva.\",\n",
    "  \"lang\": \"pt-BR\",\n",
    "  \"start_url\": \"./\",\n",
    "  \"scope\": \"./\",\n",
    "  \"display\": \"standalone\",\n",
    "  \"orientation\": \"portrait\",\n",
    "  \"background_color\": \"#f7f2e9\",\n",
    "  \"theme_color\": \"#2f3a2a\",\n",
    "  \"icons\": [\n",
    "    {\n",
    "      \"src\": \"icons/icon-192.png\",\n",
    "      \"sizes\": \"192x192\",\n",
    "      \"type\": \"image/png\",\n",
    "      \"purpose\": \"any\"\n",
    "    },\n",
    "    {\n",
    "      \"src\": \"icons/icon-512.png\",\n",
    "      \"sizes\": \"512x512\",\n",
    "      \"type\": \"image/png\",\n",
    "      \"purpose\": \"any\"\n",
    "    },\n",
    "    {\n",
    "      \"src\": \"icons/icon-maskable-512.png\",\n",
    "      \"sizes\": \"512x512\",\n",
    "      \"type\": \"image/png\",\n",
    "      \"purpose\": \"maskable\"\n",
    "    },\n",
    "    {\n",
    "      \"src\": \"icons/icon.svg\",\n",
    "      \"sizes\": \"any\",\n",
    "      \"type\": \"image/svg+xml\",\n",
    "      \"purpose\": \"any\"\n",
    "    }\n",
    "  ]\n",
    "}\n",
    ""
  ].join(""),
  },
  "/icons/icon.svg": {
    type: "image/svg+xml",
    body: [
    "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\">\n",
    "  <defs>\n",
    "    <linearGradient id=\"bg\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">\n",
    "      <stop offset=\"0\" stop-color=\"#33402c\"/>\n",
    "      <stop offset=\"1\" stop-color=\"#24301f\"/>\n",
    "    </linearGradient>\n",
    "  </defs>\n",
    "  <rect width=\"512\" height=\"512\" rx=\"112\" fill=\"url(#bg)\"/>\n",
    "  <circle cx=\"216\" cy=\"280\" r=\"104\" fill=\"none\" stroke=\"#d4b46a\" stroke-width=\"22\"/>\n",
    "  <circle cx=\"316\" cy=\"280\" r=\"104\" fill=\"none\" stroke=\"#f0ded9\" stroke-width=\"22\"/>\n",
    "  <path d=\"M244 142l22-38 22 38\" fill=\"none\" stroke=\"#d4b46a\" stroke-width=\"18\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n",
    "</svg>\n",
    ""
  ].join(""),
  },
};
